### ISSUE TITLE
Zabbiz 6 Version

### ISSUE THREAD

**Issue by MDJGyurgeiz** [diasdmhub/Asus_Merlin_Zabbix_Template#6]
Hi,
would it be possible to update the project to be supported by zabbix version 6 ?
It would be very useful as we already use it. Thank you

**Comment by MDJGyurgeiz** [comment]
ERROR

**Comment by diasdmhub** [comment]
Thanks for your comment.
This template is compatible with Zabbix 5.4 or higher.
