### ISSUE TITLE
Zabbix Asus Merlin template on Zabbix 6.4

### ISSUE THREAD

**Issue by mdiazgoncalves** [diasdmhub/Asus_Merlin_Zabbix_Template#7]
Unable to import the template on Zabbix 6.4

`Cannot import template "Asus Router by Zabbix Agent", linked template "SSH Service" does not exist.`

Probably new Zabbix version have different names?

**Comment by diasdmhub** [comment]
Zabbix 6.4 was released not too long ago and I haven't updated the template for that version yet.

The new version have different templates names and might not have the SSH Service template.

My template works out-of-the-box for Zabbix 6.2, so you can try [downloading the previous SSH Service template](https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/app/ssh_service?at=refs%2Fheads%2Frelease%2F6.2).
Save it as a yaml file and import it to your Zabbix, then import my Asus template.
