### ISSUE TITLE
Won't import into 7.0.0alpha7

### ISSUE THREAD

**Issue by elyograg** [diasdmhub/Asus_Merlin_Zabbix_Template#8]
![image](https://github.com/diasdmhub/Asus_Merlin_Zabbix_Template/assets/4984827/e4d1ba6a-a7ae-4ce7-bfcf-7b00be06009c)

This is what happens when I try to import the latest template into the latest 7.0.0 alpha release.

**Comment by diasdmhub** [comment]
The standard template modules shown in your picture are not available in Zabbix since version 6.4.
It seems that you are trying to import an older version of the template.
Did you [download the latest template version](https://github.com/diasdmhub/Asus_Merlin_Zabbix_Template/releases/tag/latest)?

The latest version has no linked templates. So, this error should not occur.
According to the latest release notes:

> _Due to OOTB template inconsistencies between Zabbix versions, templates for generic Linux modules have been removed._
> _Now, this template will focus only on specific Asus Merlin Router items._
> 
> _For generic Linux items, it is recommended to link the OOTB Linux template which offers multiple items for monitoring, including CPU, memory, disk and bandwidth information._

_Also, version 7 is not stable and it is not supported yet._

**Comment by elyograg** [comment]
I did not see that 647 version.  I opened Templates and got the v12 template.

Now it imported, but it says it is by zabbix agent ... I expected SNMP.  I have no idea how to get a zabbix agent on my router.

**Comment by elyograg** [comment]
Today I added a USB flash drive.  Installed Download Master so ipkg works.  I could not find a zabbix-agent package.

**Comment by diasdmhub** [comment]
This template was created to monitor specific Asus Merlin Router items.

As [described in the Readme](https://github.com/diasdmhub/Asus_Merlin_Zabbix_Template), there are some requirements:
> - Asus WRT Router with [Merlin firmware](https://www.asuswrt-merlin.net)
> - Entware installed
> - Zabbix agent installed

**Comment by elyograg** [comment]
Progress!  Thank you for the pointer.

I had never seen amtm or entware before.  I have an ROG GT-AX6000 router, it is running merlin.  I've only had it for a few days.

Installed entware and the zabbix agent.  Got it correctly configured with my PSK encryption.  Some of the items show up as not supported.

![image](https://github.com/diasdmhub/Asus_Merlin_Zabbix_Template/assets/4984827/fe5efefa-feb4-46fc-a680-7f7cc4092743)

All but four of the items there show `Cannot open file: [2] No such file or directory` as the info.  The four that are different are:

[Memory WebUI Total]
[Memory WebUI Used]
[Temperature Wireless 2.4GHz]
[Temperature Wireless 5.0GHz]

Those are:

`Cannot evaluate function: item "/orthanc.elyograg.org/vm.memory.size[total]" does not exist at "last(//vm.memory.size[total])".`
`Cannot evaluate function: item "/orthanc.elyograg.org/vm.memory.size[webui,total]" is not supported at "last(//vm.memory.size[webui,total])-last(//vm.memory.size[free])".`
`Value of type "string" is not suitable for value type "Numeric (float)". Value "wl: wl driver adapter not found"`
`Value of type "string" is not suitable for value type "Numeric (float)". Value "wl: Not up"`

The third one isn't really surprising ... I have the 2.4Ghz radio disabled.  I've got another router in AP mode handling 2.4Ghz for IoT stuff and , on another subnet behind a layer 3 switch.

**Comment by diasdmhub** [comment]
I added a new version with some changes that should help improving the Memory WebUI item dependencies and service descriptions.
If you could test it out, [check the latest "_pre-release_"](https://github.com/diasdmhub/Asus_Merlin_Zabbix_Template/blob/beta/Template/AsusRouter_template_648.yaml).

**Comment by elyograg** [comment]
```
elyograg@orthanc:/tmp/home/root# zabbix_agentd -V
zabbix_agentd (daemon) (Zabbix) 6.2.3
Revision 98ee88fc19d 21 September 2022

Copyright (C) 2022 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit (http://www.openssl.org/).

Compiled with OpenSSL 3.0.10 1 Aug 2023
Running with OpenSSL 3.0.10 1 Aug 2023
```

Thank you for the info.  Now I understand things a lot better than I did.

I've installed conmon and ntpmerlin.  that cleared up the conmon stuff, but not the ntpmerlin, so I disabled those items.

Installed the 648 pre-release of the template.

Adding the Linux template showed more items not supported, mostly interfaces ... I disabled those items.

The jackyaz github link in the ? hover items has the </a> tag misplaced.  Took me a few minutes to figure out why it wouldn't load the URL.
